### ISSUE TITLE
Inquiry about code release for ZipAR

### ISSUE THREAD

**Issue by NielsRogge** [ThisisBillhe/ZipAR#1]
Hello @ThisisBillhe,

I'm Niels from the Hugging Face 🤗 open-source team. I found your paper "ZipAR: Accelerating Auto-Regressive Image Generation through Spatial Locality" on Hugging Face papers (https://huggingface.co/papers/2412.04062) and was intrigued by your parallel decoding framework.  It sounds promising for significantly speeding up autoregressive image generation.

I noticed a GitHub link in the comments but couldn't access the README to verify if the code is publicly available.  Do you plan to release the code for ZipAR?

If so, we'd love to help you share it with the community on the Hugging Face Hub.  This can boost visibility and make it easier for others to explore and build upon your work.  We can also assist in adding metadata, creating a model card, and potentially setting up a demo on Spaces.

Looking forward to hearing from you!

Kind regards,
Niels

**Comment by ThisisBillhe** [comment]
> Hello @ThisisBillhe,
> 
> I'm Niels from the Hugging Face 🤗 open-source team. I found your paper "ZipAR: Accelerating Auto-Regressive Image Generation through Spatial Locality" on Hugging Face papers (https://huggingface.co/papers/2412.04062) and was intrigued by your parallel decoding framework. It sounds promising for significantly speeding up autoregressive image generation.
> 
> I noticed a GitHub link in the comments but couldn't access the README to verify if the code is publicly available. Do you plan to release the code for ZipAR?
> 
> If so, we'd love to help you share it with the community on the Hugging Face Hub. This can boost visibility and make it easier for others to explore and build upon your work. We can also assist in adding metadata, creating a model card, and potentially setting up a demo on Spaces.
> 
> Looking forward to hearing from you!
> 
> Kind regards, Niels

Hi Niels,

Thanks for your interest in our work! I have released the code of ZipAR on Lumina-mGPT(https://github.com/ThisisBillhe/ZipAR). Basically I define some hyper-parameters for ZipAR in modeling_chameleon.py and rewrite the _sample function. I appreciate your efforts to boost visibility of our work.

**Comment by NielsRogge** [comment]
Thanks! I noticed checkpoints like https://huggingface.co/Alpha-VLLM/Lumina-mGPT-7B-512 are on the hub, would you be able to add a model card? 

Particularly, would be useful to add `pipeline_tag: any-to-any` to the model cards, as well as adding https://huggingface.co/papers/2412.04062 which will automatically link the model to the paper page.

**Comment by ThisisBillhe** [comment]
I use pre-trained models and do not finetune them at all. In this case, do I need to add the model card? My method can be applied to various AR visual generation models.

**Comment by NielsRogge** [comment]
Oh I see, so you're not the author of https://github.com/Alpha-VLLM/Lumina-mGPT?

In that case, I'll reach out to them to add model cards. Thanks!
